force build
NHSDigital/electronic-prescription-service-api pull request #1825
Opened 2023-12-18 16:14 UTC by andrewrae5-nhs

## Summary

**Remove items from this list if they are not relevant. Remove this line once this has been done**

- Routine Change
- :exclamation: Breaking Change
- :robot: Operational or Infrastructure Change
- :sparkles: New Feature
- :warning: Potential issues that might be caused by this change

### Details

Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

## Reviews Required

**Check who should review this. Remove this line once this has been done**

- [x] Dev
- [ ] Test
- [ ] Tech Author
- [ ] Product Owner

## Review Checklist

:information_source: This section is to be filled in by the **reviewer**.

- [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
- [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
- [ ] I have ensured the jira ticket has been updated with the github pull request link

2023-12-20 12:00 UTC, jacksavage95 commented on packages/tool/site/client/src/pages/signPage.tsx
> +            // try to edit here
remove this comment

2023-12-20 12:03 UTC, jacksavage95 commented on packages/tool/site/client/src/pages/signPage.tsx
> +        authMethod = clone(prescription.signingOptions)
is authMethod used?

2023-12-20 12:10 UTC, jacksavage95 requested changes

2023-12-20 12:10 UTC, jacksavage95 commented on packages/tool/site/client/tests/components/prescription-summary/prescriptionSummaryView.spec.tsx
> +test.skip("Renders correctly", async () => {
Ideally we wouldn't be skipping a previously passing test - chat to Matthew Popat to see if this can be resolved

2023-12-20 12:10 UTC, jacksavage95 commented on packages/tool/site/server/src/routes/sign/uploadSignatures.ts
> +        console.log(prepareRequest)
remove

2024-01-02 11:07 UTC, jasonandtheargonauts submitted a review, later dismissed

2024-01-02 14:23 UTC, jasonandtheargonauts submitted a review, later dismissed

2024-01-09 11:53 UTC, jasonandtheargonauts approved these changes

2024-01-12 10:51 UTC, closed without merging