Update: [AEA-4475] - Alter telecom wording
NHSDigital/electronic-prescription-service-api pull request #3041
Opened 2024-12-30 11:05 UTC by wildjames

## Summary

- Routine Change

### Details

In our schema it currently says that in the telecom that phone, fax email and other can be applied and sent through to the EPS API. 

The change we want to apply is to "Phone" only.

2024-12-30 15:02 UTC, seatonator submitted a review, later dismissed

2025-01-08 09:57 UTC, MatthewPopat-NHS requested changes
Same comments apply across all 4 files

2025-01-08 09:57 UTC, MatthewPopat-NHS commented on packages/specification/schemas/components/HealthcareService/HealthcareService.yaml
> +          description: Mean of communication allowed is Phone only
It's still a means of communication even if it's singular.

2025-01-08 09:57 UTC, MatthewPopat-NHS commented on packages/specification/schemas/components/HealthcareService/HealthcareService.yaml
> +          description: Phone number for use with contact system.
"for use with contact system" doesn't really make sense if phone is the only system. Let just go with "The phone number"

2025-01-08 16:05 UTC, MatthewPopat-NHS approved these changes

2025-01-08 16:05 UTC, merged